### ISSUE TITLE
[Multiple Pages] Some screens aren't filling the full width of the main content area

### ISSUE THREAD

**Issue by keithmoss** [datawagovau/ckanext-datawagovautheme#11] opened 2019-01-23 05:21 UTC
**Dashboard**
https://uat.landgate.links.com.au/dashboard/

UAT
![screen shot 2019-01-23 at 13 20 10](https://user-images.githubusercontent.com/5944358/51584786-c1edc100-1f11-11e9-8c37-1ad83afe362e.png)

PROD
![screen shot 2019-01-23 at 13 20 15](https://user-images.githubusercontent.com/5944358/51584787-c1edc100-1f11-11e9-88f2-72c0adb6294d.png)

**Comment by keithamoss** [comment] 2019-02-08 00:22
Unable to reproduce. Assuming fixed by LD.

**Closed by keithamoss** 2019-02-08 00:22 UTC
Labels: bug
